feat: add tests suits to review, for codepipeline-actions-source
ishon19/aws-cdk pull request #1
Opened 2024-08-05 18:27 UTC by ToniDarodda

### Issue # (if applicable)

Closes #<issue number here>.

### Reason for this change

### Description of changes

### Description of how you validated changes

### Checklist
- [ ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-08-07 08:12 UTC, ishon19 requested changes

2024-08-07 08:12 UTC, ishon19 commented on packages/aws-cdk-lib/aws-codepipeline-actions/test/codepipeline-actions/codepipeline-source-actions.test.ts
Thanks @ToniDarodda, since the feature request is regarding the `CodeConnections` as source, can we create a test similar to [`codestar-connections-source-action.test.ts`](https://github.com/ishon19/aws-cdk/blob/b83d954ba56f727edf1beee1a81c02eb7730dc0a/packages/aws-cdk-lib/aws-codepipeline-actions/test/codestar-connections/codestar-connections-source-action.test.ts) file, and use our newly created `CodeConnections` option test and place it in `aws-codepipeline-actions/test/codeconnections` directory?

2024-08-07 10:33 UTC, ToniDarodda commented on packages/aws-cdk-lib/aws-codepipeline-actions/test/codepipeline-actions/codepipeline-source-actions.test.ts
Yeah, of course, do you want me to delete the old one? the [codepipeline-source-actions.test.ts](https://github.com/ishon19/aws-cdk/blob/b83d954ba56f727edf1beee1a81c02eb7730dc0a/packages/aws-cdk-lib/aws-codepipeline-actions/test/codepipeline-actions/codepipeline-source-actions.test.ts)

2024-08-07 15:35 UTC, ToniDarodda commented on packages/aws-cdk-lib/aws-codepipeline-actions/test/codepipeline-actions/codepipeline-source-actions.test.ts
@ishon19

2024-08-07 21:16 UTC, ishon19 commented on packages/aws-cdk-lib/aws-codepipeline-actions/test/codepipeline-actions/codepipeline-source-actions.test.ts
Hi @ToniDarodda sorry for the late response! Busy day at work as usual. You can keep it for now, before we get the upstream PR ready to merge we can do a quick review to get rid of non-relevant tests.

2024-08-08 06:20 UTC, ToniDarodda commented on packages/aws-cdk-lib/aws-codepipeline-actions/test/codepipeline-actions/codepipeline-source-actions.test.ts
@ishon19 yeah sure

2024-08-08 17:20 UTC, ishon19 approved these changes
LGTM!

2024-08-08 17:20 UTC, ishon19 commented
Thanks @ToniDarodda, I am merging the changes to my branch, then we can check if we need to do anything in the main PR.

2024-08-08 17:21 UTC, merged